# Generated by Django 6.0 on 2025-12-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_evento_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='certificado_carga_horaria_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='certificado_evento_nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='certificado_local',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
