# Generated by Django 6.0 on 2025-12-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_inscricao_certificado_carga_horaria_minutos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='participante_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='participante_first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='participante_last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
